### ISSUE TITLE
Mirroring vs extending desktop?

### ISSUE THREAD

**Issue by oyd11** [borzunov/remoteink#15]
This is really cool, it works and mirrors part of the desktop, I couldn't find this in the guide, is there a simple way to extend the desktop to the Pocketbook rather than mirror it? Or running a separate X-Server for it?

**Comment by borzunov** [comment]
Hi @oyd11!

I think it should be possible to create one more virtual display in X11 (I'd google a recipe for that), then forward it to the reader with remoteink using the `$DISPLAY` env variable. Unfortunately, right now I don't have a Linux laptop and a Pocketbook to test it myself.

If you manage to make it work, please share the commands for that. I agree that it is a useful use case and will be happy to add the instructions to the readme.

**Comment by oyd11** [comment]
Cool! yes, I'll try googling exactly that; so you were using it primarily to mirror part of the display?
right now my main work laptop is Linux and I have a Pocketbook, so I thought it's quite cool to use for a display for logs for example (`tail -f ...`) or for reading documentation etc; 

I'll make a PR for the README if I get it working;

BTW: do you know whether I can run TCP over USB on the Pocketbook 623? does that depend on the firmware/can I install it there? I don't see this option on the menu there, and I have two 623's, where `WiFi` seems to have died on one of them...

**Comment by borzunov** [comment]
> so you were using it primarily to mirror part of the display?

Yup, I mostly used it instead of the display on my laptop or Raspberry Pi :)

> BTW: do you know whether I can run TCP over USB on the Pocketbook 623? does that depend on the firmware/can I install it there?

It depends on the firmware, and I know that the USB option is absent in some firmware versions. I recall posts where other people tried to install an older/newer version of the firmware (or a modified one) to get the USB option back, but I don't know if they succeeded. These posts were either in [this thread](https://www.mobileread.com/forums/showthread.php?t=256203#12), or somewhere else on the MobileRead forums.
