### ISSUE TITLE
Error on request to X server

### ISSUE THREAD

**Issue by 150495** [borzunov/remoteink#2]
Hi, first let me congratulate you for this excellent program! I'm running archlinux and make sure to follow every step but it doesn't work. In journalctl the following message is displayed: Error on request to X server. I've tried different ports, firewall configuration, but with no success. The e-reader doesn't show anything and after two or three minutes gives the message: Failed to connect to 10.0.0."something":9312.

Could you please help me? Thanks a lot!

**Comment by borzunov** [comment]
Hi, I'm glad that this program may be useful for you!

Firstly, to make sure that your connection and firewall settings are all right, please do the following:
1. Install PoTerm to your reader from [this archive](http://fedorchenko.net/src/poterm-2.0.1-Pro.zip) (copy `poterm.app` to the `applications` folder)
2. Run on the computer:
   
   ```
   $ sudo remoteinkd stop
   $ nc -lvv 0.0.0.0 9132
   ```
   
   Then print something like "Hello reader" in the terminal and press Enter.
3. Connect to the network on the reader, run PoTerm, tap a screen, select "Command" item, and then write the following command (substitute your IP instead of `10.0.0.X`):
   
   ```
   nc -vv 10.0.0.X 9132
   ```
   
   If it's OK, you will see line "Hello reader" on your reader. If not, please describe the output you will see.

Secondly, try to install a special version of the server where I made error messages more verbose. Clone another branch of this repository:

```
$ git clone -b debug https://github.com/borzunov/remoteink.git
$ cd remoteink/server
$ make
$ sudo make install
```

Before running, remove or comment out all entries in `[Shortcuts]` section of `/etc/remoteinkd/config.ini` file to avoid problems with binding shortcuts. Note that you should run `sudo remoteinkd start` inside a usual X session (not from a virtual terminal invoked by Ctrl+Alt+Fn keys). Then try to run the server and check logs again.

Please write whether the problem persists.

**Comment by 150495** [comment]
Hi borzunov, thank you very much for your help! I realize that I didn't mention which pocketbook model I have, which is Pocketbook Pro 912 (AFAIK it's the same as 903). 

In step 3) in Poterm app, I get: "nc: invalid option --v
BusyBox v.1.16.1 (2010...) multi-call binary
Usage: nc [-iN] [-wN] [-l] [-p PORT] [-f FILENAME|IPADDR PORT] [-e PROG]
Open a pipe to IP:port or file
Options:..."

If I write: nc 10.0.0.5 9132 (without -vv) and the firewall is off, I get: "can't connect to remote host (10.0.0.5), Connection refused". If the firewall is on, I get this in journalctl: [UFW BLOCK] IN=wlp1s0 OUT= MAC= SRC=fe80:0000:0000:0000:52b7:c3ff:fe28:38e0 DST=ff02:0000:0000

[UFW BLOCK] IN=wlp1s0 OUT= MAC=50:b7:c3:28:38:e0:00:90:a2:28:45:c4:08:00 SRC=10.0.0.7 DST=10.0.

I also tried nc -l 10.0.0.5 9132, nc -ll -e 10.0.0.5 9132, nc -l -e 10.0.0.5 9132, but nothing worked (in the sense that no "Hello reader" showed).

With respect to the special server, I came up with the following:

1) When firewall is on, the messages in journalctl are:
Monitor resolution: 1366x768
Server listens on 0.0.0.0:9312
[UFW BLOCK] IN=wlp1s0 OUT= MAC=50:b7:c3:28:38:e0:00:90:a2:28:45:c4:08:00 SRC=10.0.0.7 DST=10.0    (this last line is displayed four times)

2) When firewall is off, it is displayed the following:
Monitor resolution: 1366x768
Server listens on 0.0.0.0:9312
kernel: TCP: request_sock_TCP: Possible SYN flooding on port 9312. Dropping request.  Check SNMP count

Thanks a lot, and I hope I'm not taking too much of your time. Regards

**Comment by borzunov** [comment]
Yeah, -vv flag in the command for the reader was redundant. Have you got any journalctl messages when you received "Connection refused" error?

I suppose the problem is that a reader's connection is dropped by your system as mentioned in this error:

```
kernel: TCP: request_sock_TCP: Possible SYN flooding on port 9312. Dropping request. Check SNMP count
```

I made a small fix in the code that may be related to this (you can clone `debug` branch again and reinstall the server). If this doesn't help, I would suggest you try to adjust your network configuration (there're some advices if you google the error above) or try another OS.

**Comment by 150495** [comment]
It works!! I cloned and installed this new server and tried with firewall on and it didn't work, so I added rules to port 9312 and now it works really well! So I think the solution is your fix. It's an awesome app! Thank you very much both for the app and your great help!

**Comment by borzunov** [comment]
Good! I'll merge this fix into master then.
